/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:dc8d2437-47e6-43e6-9d03-7b57d5811714",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_eJGnIQmVh",
    "aws_user_pools_web_client_id": "3etqv0p75oaerfqfq5iqu6n0l5",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://grwujfdypfbeteuxycihfzbe24.appsync-api.ap-northeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-33b6itt5rnexxifoz456xlbxhe"
};


export default awsmobile;
